server {
    listen 80;
    listen [::]:80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location ~ ^/(?:en/)?products/app-store/lobe-chat(?:-db)?/?$ {
        return 308 /products/app-store/lobehub/;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
}
